steps:

- id: 'Running docker-compose'
  name: 'gcr.io/$PROJECT_ID/docker-compose:1.28.2'
  args: ['-f', 'docker-compose.prod.yaml', 'up', '-d']

- id: 'Running docker ps'
  name: 'gcr.io/cloud-builders/docker'
  args: ['ps']

- id: 'Running composer'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'composer', 'install']

- id: 'Copying .env'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'cp', '.env.example', '.env']

- id: 'Generate key'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'php', '/var/www/artisan', 'key:generate']
